[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$8z5nTGlNqVWK8Z5Tylmr1Q$Yn1QiIbHplYmQNWO0/9BJZ57O3NInoJfT20EhEPQBPE0VvM06VH6LNYRWVp2Ogpp/cu0xMg91xuB5KF/3y8RfA

